// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACi893A8qafr4lqaXW0EdnsVyVUhv-xfA',
    appId: '1:241002232748:web:5c2b67a861726d91e4d809',
    messagingSenderId: '241002232748',
    projectId: 'workshop-manager-5f2f7',
    authDomain: 'workshop-manager-5f2f7.firebaseapp.com',
    storageBucket: 'workshop-manager-5f2f7.firebasestorage.app',
    measurementId: 'G-2Z770GCLLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzaKUDe7c-QLp9rHXbkMzmKFznVP3U7Rw',
    appId: '1:241002232748:android:b4598e8a03af0968e4d809',
    messagingSenderId: '241002232748',
    projectId: 'workshop-manager-5f2f7',
    storageBucket: 'workshop-manager-5f2f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP2u-XjRnsQgc6bsUP3v9z-oc7bBU2BZY',
    appId: '1:241002232748:ios:298f15ae8cde1737e4d809',
    messagingSenderId: '241002232748',
    projectId: 'workshop-manager-5f2f7',
    storageBucket: 'workshop-manager-5f2f7.firebasestorage.app',
    iosBundleId: 'com.example.workshopManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP2u-XjRnsQgc6bsUP3v9z-oc7bBU2BZY',
    appId: '1:241002232748:ios:298f15ae8cde1737e4d809',
    messagingSenderId: '241002232748',
    projectId: 'workshop-manager-5f2f7',
    storageBucket: 'workshop-manager-5f2f7.firebasestorage.app',
    iosBundleId: 'com.example.workshopManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACi893A8qafr4lqaXW0EdnsVyVUhv-xfA',
    appId: '1:241002232748:web:74024e1f85441e4ee4d809',
    messagingSenderId: '241002232748',
    projectId: 'workshop-manager-5f2f7',
    authDomain: 'workshop-manager-5f2f7.firebaseapp.com',
    storageBucket: 'workshop-manager-5f2f7.firebasestorage.app',
    measurementId: 'G-BJ5P9M8ZM1',
  );
}
